;;; -*- Mode: LISP; package:maxima; syntax:common-lisp; -*- 
(in-package :maxima)
(|MAXIMA|::|DSKSETQ| |MAXIMA|::|$varsC| '((|MAXIMA|::|MLIST| |MAXIMA|::|SIMP|) |MAXIMA|::|$X|)) 
(|MAXIMA|::|ADD2LNC| '|MAXIMA|::|$varsC| |MAXIMA|::|$VALUES|) 
(|MAXIMA|::|DSKSETQ| |MAXIMA|::|$varsP|
 '((|MAXIMA|::|MLIST| |MAXIMA|::|SIMP|) |MAXIMA|::|$X| |MAXIMA|::|$VX| |MAXIMA|::|$VY|
   |MAXIMA|::|$VZ|)) 
(|MAXIMA|::|ADD2LNC| '|MAXIMA|::|$varsP| |MAXIMA|::|$VALUES|) 
(|MAXIMA|::|DSKSETQ| |MAXIMA|::|$basisC|
 '((|MAXIMA|::|MLIST| |MAXIMA|::|SIMP|
    (23. "/work/03485/jonroelt/maxima/gkylcas/maxima/g0/basis-precalc/basis-pre-calc-hybrid.mac"
     |MAXIMA|::|SRC| |MAXIMA|::|$writeHybBasisToFile| 16.))
   ((|MAXIMA|::|MLIST| |MAXIMA|::|SIMP|
     (33. "/work/03485/jonroelt/maxima/gkylcas/maxima/g0/modal-basis.mac" |MAXIMA|::|SRC|
      |MAXIMA|::|$gsOrthoNorm| 31.))
    ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|) 2. ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) -1. 2.))
    ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|)
     ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|) 2. ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) -1. 2.))
     ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|) 3. ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 2.))
     |MAXIMA|::|$X|)))) 
(|MAXIMA|::|ADD2LNC| '|MAXIMA|::|$basisC| |MAXIMA|::|$VALUES|) 
(|MAXIMA|::|DSKSETQ| |MAXIMA|::|$basisP|
 '((|MAXIMA|::|MLIST| |MAXIMA|::|SIMP|
    (29. #1="/work/03485/jonroelt/maxima/gkylcas/maxima/g0/basis-precalc/basis-pre-calc-hybrid.mac"
     |MAXIMA|::|SRC| |MAXIMA|::|$writeHybBasisToFile| 16.))
   ((|MAXIMA|::|MLIST| |MAXIMA|::|SIMP|
     (33. "/work/03485/jonroelt/maxima/gkylcas/maxima/g0/modal-basis.mac" |MAXIMA|::|SRC|
      |MAXIMA|::|$gsOrthoNorm| 31.))
    ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 4.)
    (#2=(|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|) ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 4.)
     ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|) 3. ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 2.))
     |MAXIMA|::|$X|)
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 4.)
     ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|) 3. ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 2.))
     |MAXIMA|::|$VX|)
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 4.)
     ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|) 3. ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 2.))
     |MAXIMA|::|$VY|)
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 4.)
     ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|) 3. ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 2.))
     |MAXIMA|::|$VZ|)
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 3. 4.) |MAXIMA|::|$VX| |MAXIMA|::|$X|)
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 3. 4.) |MAXIMA|::|$VY| |MAXIMA|::|$X|)
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 3. 4.) |MAXIMA|::|$VX| |MAXIMA|::|$VY|)
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 3. 4.) |MAXIMA|::|$VZ| |MAXIMA|::|$X|)
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 3. 4.) |MAXIMA|::|$VX| |MAXIMA|::|$VZ|)
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 3. 4.) |MAXIMA|::|$VY| |MAXIMA|::|$VZ|)
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 4.)
     ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|) 3. ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 3. 2.))
     |MAXIMA|::|$VX| |MAXIMA|::|$VY| |MAXIMA|::|$X|)
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 4.)
     ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|) 3. ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 3. 2.))
     |MAXIMA|::|$VX| |MAXIMA|::|$VZ| |MAXIMA|::|$X|)
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 4.)
     ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|) 3. ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 3. 2.))
     |MAXIMA|::|$VY| |MAXIMA|::|$VZ| |MAXIMA|::|$X|)
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 4.)
     ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|) 3. ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 3. 2.))
     |MAXIMA|::|$VX| |MAXIMA|::|$VY| |MAXIMA|::|$VZ|)
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 9. 4.) |MAXIMA|::|$VX| |MAXIMA|::|$VY| |MAXIMA|::|$VZ|
     |MAXIMA|::|$X|)
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 3. 8.)
     ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|) 5. ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 2.))
     ((|MAXIMA|::|MPLUS| |MAXIMA|::|SIMP|) ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) -1. 3.)
      ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|
        (27. #1# |MAXIMA|::|SRC| |MAXIMA|::|$writeHybBasisToFile| 16.))
       |MAXIMA|::|$VX| 2.)))
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 3. 8.)
     ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|) 15. ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 2.))
     ((|MAXIMA|::|MPLUS| |MAXIMA|::|SIMP|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|) ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) -1. 3.)
       |MAXIMA|::|$X|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|)
       ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|
         (27. #1# |MAXIMA|::|SRC| |MAXIMA|::|$writeHybBasisToFile| 16.))
        |MAXIMA|::|$VX| 2.)
       |MAXIMA|::|$X|)))
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 3. 8.)
     ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|) 15. ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 2.))
     ((|MAXIMA|::|MPLUS| |MAXIMA|::|SIMP|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|) ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) -1. 3.)
       |MAXIMA|::|$VY|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|)
       ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|
         (27. #1# |MAXIMA|::|SRC| |MAXIMA|::|$writeHybBasisToFile| 16.))
        |MAXIMA|::|$VX| 2.)
       |MAXIMA|::|$VY|)))
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 3. 8.)
     ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|) 15. ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 2.))
     ((|MAXIMA|::|MPLUS| |MAXIMA|::|SIMP|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|) ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) -1. 3.)
       |MAXIMA|::|$VZ|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|)
       ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|
         (27. #1# |MAXIMA|::|SRC| |MAXIMA|::|$writeHybBasisToFile| 16.))
        |MAXIMA|::|$VX| 2.)
       |MAXIMA|::|$VZ|)))
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 9. 8.)
     ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|) 5. ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 2.))
     ((|MAXIMA|::|MPLUS| |MAXIMA|::|SIMP|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|) ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) -1. 3.)
       |MAXIMA|::|$VY| |MAXIMA|::|$X|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|)
       ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|
         (27. #1# |MAXIMA|::|SRC| |MAXIMA|::|$writeHybBasisToFile| 16.))
        |MAXIMA|::|$VX| 2.)
       |MAXIMA|::|$VY| |MAXIMA|::|$X|)))
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 9. 8.)
     ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|) 5. ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 2.))
     ((|MAXIMA|::|MPLUS| |MAXIMA|::|SIMP|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|) ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) -1. 3.)
       |MAXIMA|::|$VZ| |MAXIMA|::|$X|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|)
       ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|
         (27. #1# |MAXIMA|::|SRC| |MAXIMA|::|$writeHybBasisToFile| 16.))
        |MAXIMA|::|$VX| 2.)
       |MAXIMA|::|$VZ| |MAXIMA|::|$X|)))
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 9. 8.)
     ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|) 5. ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 2.))
     ((|MAXIMA|::|MPLUS| |MAXIMA|::|SIMP|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|) ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) -1. 3.)
       |MAXIMA|::|$VY| |MAXIMA|::|$VZ|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|)
       ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|
         (27. #1# |MAXIMA|::|SRC| |MAXIMA|::|$writeHybBasisToFile| 16.))
        |MAXIMA|::|$VX| 2.)
       |MAXIMA|::|$VY| |MAXIMA|::|$VZ|)))
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 9. 8.)
     ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|) 15. ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 2.))
     ((|MAXIMA|::|MPLUS| |MAXIMA|::|SIMP|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|) ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) -1. 3.)
       |MAXIMA|::|$VY| |MAXIMA|::|$VZ| |MAXIMA|::|$X|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|)
       ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|
         (27. #1# |MAXIMA|::|SRC| |MAXIMA|::|$writeHybBasisToFile| 16.))
        |MAXIMA|::|$VX| 2.)
       |MAXIMA|::|$VY| |MAXIMA|::|$VZ| |MAXIMA|::|$X|)))
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 3. 8.)
     ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|) 5. ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 2.))
     ((|MAXIMA|::|MPLUS| |MAXIMA|::|SIMP|) ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) -1. 3.)
      ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|
        (27. #1# |MAXIMA|::|SRC| |MAXIMA|::|$writeHybBasisToFile| 16.))
       |MAXIMA|::|$VY| 2.)))
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 3. 8.)
     ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|) 15. ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 2.))
     ((|MAXIMA|::|MPLUS| |MAXIMA|::|SIMP|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|) ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) -1. 3.)
       |MAXIMA|::|$X|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|)
       ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|
         (27. #1# |MAXIMA|::|SRC| |MAXIMA|::|$writeHybBasisToFile| 16.))
        |MAXIMA|::|$VY| 2.)
       |MAXIMA|::|$X|)))
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 3. 8.)
     ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|) 15. ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 2.))
     ((|MAXIMA|::|MPLUS| |MAXIMA|::|SIMP|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|) ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) -1. 3.)
       |MAXIMA|::|$VX|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|) |MAXIMA|::|$VX|
       ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|
         (27. #1# |MAXIMA|::|SRC| |MAXIMA|::|$writeHybBasisToFile| 16.))
        |MAXIMA|::|$VY| 2.))))
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 3. 8.)
     ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|) 15. ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 2.))
     ((|MAXIMA|::|MPLUS| |MAXIMA|::|SIMP|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|) ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) -1. 3.)
       |MAXIMA|::|$VZ|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|)
       ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|
         (27. #1# |MAXIMA|::|SRC| |MAXIMA|::|$writeHybBasisToFile| 16.))
        |MAXIMA|::|$VY| 2.)
       |MAXIMA|::|$VZ|)))
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 9. 8.)
     ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|) 5. ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 2.))
     ((|MAXIMA|::|MPLUS| |MAXIMA|::|SIMP|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|) ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) -1. 3.)
       |MAXIMA|::|$VX| |MAXIMA|::|$X|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|) |MAXIMA|::|$VX|
       ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|
         (27. #1# |MAXIMA|::|SRC| |MAXIMA|::|$writeHybBasisToFile| 16.))
        |MAXIMA|::|$VY| 2.)
       |MAXIMA|::|$X|)))
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 9. 8.)
     ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|) 5. ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 2.))
     ((|MAXIMA|::|MPLUS| |MAXIMA|::|SIMP|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|) ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) -1. 3.)
       |MAXIMA|::|$VZ| |MAXIMA|::|$X|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|)
       ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|
         (27. #1# |MAXIMA|::|SRC| |MAXIMA|::|$writeHybBasisToFile| 16.))
        |MAXIMA|::|$VY| 2.)
       |MAXIMA|::|$VZ| |MAXIMA|::|$X|)))
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 9. 8.)
     ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|) 5. ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 2.))
     ((|MAXIMA|::|MPLUS| |MAXIMA|::|SIMP|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|) ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) -1. 3.)
       |MAXIMA|::|$VX| |MAXIMA|::|$VZ|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|) |MAXIMA|::|$VX|
       ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|
         (27. #1# |MAXIMA|::|SRC| |MAXIMA|::|$writeHybBasisToFile| 16.))
        |MAXIMA|::|$VY| 2.)
       |MAXIMA|::|$VZ|)))
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 9. 8.)
     ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|) 15. ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 2.))
     ((|MAXIMA|::|MPLUS| |MAXIMA|::|SIMP|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|) ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) -1. 3.)
       |MAXIMA|::|$VX| |MAXIMA|::|$VZ| |MAXIMA|::|$X|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|) |MAXIMA|::|$VX|
       ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|
         (27. #1# |MAXIMA|::|SRC| |MAXIMA|::|$writeHybBasisToFile| 16.))
        |MAXIMA|::|$VY| 2.)
       |MAXIMA|::|$VZ| |MAXIMA|::|$X|)))
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 3. 8.)
     ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|) 5. ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 2.))
     ((|MAXIMA|::|MPLUS| |MAXIMA|::|SIMP|) ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) -1. 3.)
      ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|
        (27. #1# |MAXIMA|::|SRC| |MAXIMA|::|$writeHybBasisToFile| 16.))
       |MAXIMA|::|$VZ| 2.)))
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 3. 8.)
     ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|) 15. ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 2.))
     ((|MAXIMA|::|MPLUS| |MAXIMA|::|SIMP|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|) ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) -1. 3.)
       |MAXIMA|::|$X|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|)
       ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|
         (27. #1# |MAXIMA|::|SRC| |MAXIMA|::|$writeHybBasisToFile| 16.))
        |MAXIMA|::|$VZ| 2.)
       |MAXIMA|::|$X|)))
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 3. 8.)
     ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|) 15. ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 2.))
     ((|MAXIMA|::|MPLUS| |MAXIMA|::|SIMP|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|) ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) -1. 3.)
       |MAXIMA|::|$VX|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|) |MAXIMA|::|$VX|
       ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|
         (27. #1# |MAXIMA|::|SRC| |MAXIMA|::|$writeHybBasisToFile| 16.))
        |MAXIMA|::|$VZ| 2.))))
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 3. 8.)
     ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|) 15. ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 2.))
     ((|MAXIMA|::|MPLUS| |MAXIMA|::|SIMP|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|) ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) -1. 3.)
       |MAXIMA|::|$VY|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|) |MAXIMA|::|$VY|
       ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|
         (27. #1# |MAXIMA|::|SRC| |MAXIMA|::|$writeHybBasisToFile| 16.))
        |MAXIMA|::|$VZ| 2.))))
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 9. 8.)
     ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|) 5. ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 2.))
     ((|MAXIMA|::|MPLUS| |MAXIMA|::|SIMP|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|) ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) -1. 3.)
       |MAXIMA|::|$VX| |MAXIMA|::|$X|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|) |MAXIMA|::|$VX|
       ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|
         (27. #1# |MAXIMA|::|SRC| |MAXIMA|::|$writeHybBasisToFile| 16.))
        |MAXIMA|::|$VZ| 2.)
       |MAXIMA|::|$X|)))
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 9. 8.)
     ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|) 5. ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 2.))
     ((|MAXIMA|::|MPLUS| |MAXIMA|::|SIMP|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|) ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) -1. 3.)
       |MAXIMA|::|$VY| |MAXIMA|::|$X|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|) |MAXIMA|::|$VY|
       ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|
         (27. #1# |MAXIMA|::|SRC| |MAXIMA|::|$writeHybBasisToFile| 16.))
        |MAXIMA|::|$VZ| 2.)
       |MAXIMA|::|$X|)))
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 9. 8.)
     ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|) 5. ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 2.))
     ((|MAXIMA|::|MPLUS| |MAXIMA|::|SIMP|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|) ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) -1. 3.)
       |MAXIMA|::|$VX| |MAXIMA|::|$VY|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|) |MAXIMA|::|$VX| |MAXIMA|::|$VY|
       ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|
         (27. #1# |MAXIMA|::|SRC| |MAXIMA|::|$writeHybBasisToFile| 16.))
        |MAXIMA|::|$VZ| 2.))))
    (#2# ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 9. 8.)
     ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|) 15. ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) 1. 2.))
     ((|MAXIMA|::|MPLUS| |MAXIMA|::|SIMP|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|) ((|MAXIMA|::|RAT| |MAXIMA|::|SIMP|) -1. 3.)
       |MAXIMA|::|$VX| |MAXIMA|::|$VY| |MAXIMA|::|$X|)
      ((|MAXIMA|::|MTIMES| |MAXIMA|::|SIMP|) |MAXIMA|::|$VX| |MAXIMA|::|$VY|
       ((|MAXIMA|::|MEXPT| |MAXIMA|::|SIMP|
         (27. #1# |MAXIMA|::|SRC| |MAXIMA|::|$writeHybBasisToFile| 16.))
        |MAXIMA|::|$VZ| 2.)
       |MAXIMA|::|$X|)))))) 
(|MAXIMA|::|ADD2LNC| '|MAXIMA|::|$basisP| |MAXIMA|::|$VALUES|) 