cvars : [X, Y, Z]$
cvars_name : ["x","y","z"]$

printPrototypes() := block([],
  pmax:3,
  for ci : 1 thru 3 do (
    for pi : 1 thru pmax do (
      printf(fh, "GKYL_CU_DH double isoeuler_vol_~ax~av_ser_p~a(const double *w, const double *dxv, const double vth, const double *uvar, const double *statevec, double* GKYL_RESTRICT out); ~%", ci, ci, pi),
      for si : 1 thru ci do (
        dirlabel : cvars[si],
        printf(fh, "GKYL_CU_DH void isoeuler_surf~a_~ax~av_ser_p~a(const double *w, const double *dxv, double vth, const double *uvarl, const double *uvarc, const double *uvarr, const double *statevecl, const double *statevecc, const double *statevecr, double* GKYL_RESTRICT out); ~%", cvars_name[ci], ci, ci, pi)
      ),
      printf(fh, "~%")
    )
  )
)$

fh : openw("~/max-out/IsoEulerModDecl.h")$
printf(fh, "#ifndef ISOEULER_MOD_DECL_H ~%")$
printf(fh, "#define ISOEULER_MOD_DECL_H ~%")$
printf(fh, "#include <cmath> ~%")$
printPrototypes()$
printf(fh, "} ~%")$
printf(fh, "#endif ~%")$
close(fh)$

/* fh : openw("~/max-out/ISOEulerCdef.lua")$
printf(fh, "local ffi = require \"ffi\" ~%~%")$
printf(fh, "ffi.cdef [[~%")$
printPrototypes()$
printf(fh, "]]~%")$
close(fh)$ */
