/*
   Create kernels for the volume term of the gyrokinetic collisionless terms.
*/

load("modal-basis")$
load("out-scripts")$
load(stringproc)$
load("scifac")$
load("utilities_gyrokinetic")$
load("utilities")$
fpprec : 24$

buildGKVolKernel(fh, funcNm, cdim, vdim, basisFun, polyOrder, varsInB, no_by) := block(
  [pdim,varsC,bC,varsP,bP,varsV,vSub,numC,numP,varLabel,d,rdx2vec,rdv2vec,allVarLabelsC,
   bmagBasis,ignoreVars,inFlds_e,cmag_e,b_x_e,b_y_e,b_z_e,vmap_e,BstardBmag_e,
   hamil_e,pbAuxFlds,alphaSum_e,vd,dir,dirLabel,wDir,rdDirVar2,vmap_prime_fac,dirVar,
   dirVar_phys,alpha_e,alpha_c,alphaLabel,alphaNoZero_c,alphaDotGradBasis_e,f_e,volTerm_c, 
   alphaJf_e, Jf_e, replaceListHamil, replaceListVpar,hamil2_c,isqlist,mvpar_e,mvparsq_e,
   replaceList,dvparSimp,phi_e,bmag_e,dualcurlbhatoverB_x_e,dualcurlbhatoverB_y_e,dualcurlbhatoverB_z_e,
   rtg33inv_e,bioverJB_x_e,bioverJB_y_e,bioverJB_z_e,dualcurlbhatoverB_list,bioverJB_list,
   dualcurlbhatoverB_vec,bioverJB_vec,vmapSq_e,vmap_prime_e,hamilCvar,hamilNoZero_c,hamil_c,
   xidx,yidx,zidx,vidx,vpardim,dH_dx,dH_dy,dH_dz,dH_dvpar,gradH_vec,gradH_list,
   bcrossgradH_x,bcrossgradH_y,bcrossgradH_z,bcrossgradH_vec,bcrossgradH_list,i,k,curvdriftdir,clst],

  kill(varsC,varsP,bC,bP),
  pdim : cdim+vdim,

  [varsC,bC,varsP,bP,vSub] : loadGkBasis(basisFun, cdim, vdim, polyOrder),
  numC : length(bC),  numP : length(bP), 

  varLabel : makelist(string(varsP[d]),d,1,pdim),

  print("Working on ", funcNm),
  printf(fh, "GKYL_CU_DH double ~a(const double *w, const double *dxv, const double *vmap, const double *vmapSq,
    const double q_, const double m_, const double *bmag, const double *phi,
    const double *dualcurlbhatoverB, const double *rtg33inv, const double *bioverJB,
    const double *fin, double* GKYL_RESTRICT out) ~%{ ~%", funcNm),
  printf(fh, "  // w[NDIM]: cell-center.~%"),
  printf(fh, "  // dxv[NDIM]: cell length.~%"),
  printf(fh, "  // vmap: velocity space mapping.~%"),
  printf(fh, "  // vmapSq: velocity space mapping squared.~%"),
  printf(fh, "  // q_,m_: species charge and mass.~%"),
  printf(fh, "  // bmag: magnetic field amplitude.~%"),
  printf(fh, "  // phi: electrostatic potential .~%"),
  printf(fh, "  // fin: Distribution function.~%"),
  printf(fh, "  // out: output increment.~%"),
  printf(fh, "~%"),

  /* Declare cell-center variables and variables multiplying gradients. */
  for d : 1 thru pdim do (
    printf(fh, "  double rd~a2 = 2.0/dxv[~a];~%", varLabel[d], d-1)
  ),
  printf(fh, "~%"),
  rdx2vec : makelist(eval_string(sconcat("rd",varLabel[i],"2")),i,1,cdim),
  rdv2vec : makelist(eval_string(sconcat("rd",varLabel[i],"2")),i,cdim+1,pdim),

  /* Declare variables with squared of cell centers and rdx2 variables (only need vpar^2). */
  printf(fh, "  double rdvpar2Sq = rdvpar2*rdvpar2;~%"),
  printf(fh, "  double dvparSq = dxv[~a]*dxv[~a];~%", cdim, cdim),
  printf(fh, "~%"),
  replaceList : [rdvpar2^2=rdvpar2Sq,dxv[cdim]^2=dvparSq,rdvpar2Sq=4/dvparSq],
  dvparSimp : append(makelist(dxv[i-1]=2/eval_string(sconcat("rd",varLabel[i],"2")),i,1,pdim),
                     [dvparSq=4/rdvpar2Sq]),

  /* Store indices of the coordinate directions. */
  if cdim = 3 then (
    xidx : 1, yidx : 2, zidx : 3, vidx : 4
  ) else if cdim = 2 then (
    xidx : 1, zidx : 2, vidx : 3
  ) else if cdim = 1 then (
    zidx : 1, vidx : 2
  ),

  /* Create pointers to the components of b_i. */
  allVarLabelsC : ["x","y","z"],
  for d : 1 thru 3 do (
    printf(fh, "  const double *bioverJB_~a = &bioverJB[~a]; ~%", allVarLabelsC[d], numC*(d-1))
  ),
  printf(fh, "~%"),

  /* Create pointers to the components of dualcurlbhatoverB. */
  allVarLabelsC : ["x","y","z"],
  for d : 1 thru 3 do (
    printf(fh, "  const double *dualcurlbhatoverB_~a = &dualcurlbhatoverB[~a]; ~%", allVarLabelsC[d], numC*(d-1))
  ),
  printf(fh, "~%"),

  /* Axisymmetric basis (independent of y). */
  bmagBasis : getAxisymmetricConfBasis(bC),
  /* Expand input fields for Hamiltonian calculation */
  phi_e     : doExpand1(phi,bC),
  bmag_e : doExpand1(bmag, bmagBasis),
  dualcurlbhatoverB_x_e : doExpand1(dualcurlbhatoverB_x, bmagBasis),
  dualcurlbhatoverB_y_e : doExpand1(dualcurlbhatoverB_y, bmagBasis),
  dualcurlbhatoverB_z_e : doExpand1(dualcurlbhatoverB_z, bmagBasis),
  rtg33inv_e : doExpand1(rtg33inv, bmagBasis),
  bioverJB_x_e : doExpand1(bioverJB_x, bmagBasis),
  bioverJB_y_e : doExpand1(bioverJB_y, bmagBasis),
  bioverJB_z_e : doExpand1(bioverJB_z, bmagBasis),

  dualcurlbhatoverB_list : [dualcurlbhatoverB_x_e, dualcurlbhatoverB_y_e, dualcurlbhatoverB_z_e],
  bioverJB_list : [bioverJB_x_e, bioverJB_y_e, bioverJB_z_e],
  if cdim = 3 then (
    dualcurlbhatoverB_vec : [dualcurlbhatoverB_x_e, dualcurlbhatoverB_y_e, dualcurlbhatoverB_z_e],
    bioverJB_vec : [bioverJB_x_e, bioverJB_y_e, bioverJB_z_e]
  ) else if cdim = 2 then (
    dualcurlbhatoverB_vec : [dualcurlbhatoverB_x_e, dualcurlbhatoverB_z_e],
    bioverJB_vec : [bioverJB_x_e, bioverJB_z_e]
  ) else if cdim = 1 then (
    dualcurlbhatoverB_vec : [dualcurlbhatoverB_z_e],
    bioverJB_vec : [bioverJB_z_e]
  ),

  /* Velocity mapping fields. */
  [vmap_e,vmapSq_e,vmap_prime_e] : expandVmapFields(varsP),

  /* Redefine vmap_prime to exploit the relationship between it and vmap. */
  vmap_prime_e : makelist(diff(vmap_e[d],varsP[cdim+d]),d,1,vdim),

  /* Finally write out the hamiltonian*/
  hamil_e : q_*phi_e + (1/2)*m_*vmapSq_e[1],
  if vdim > 1 then ( hamil_e : hamil_e + vmap_e[2]*bmag_e ),
  hamil_c : calcInnerProdList(varsP, 1, bP, hamil_e),
  printf(fh, "  double hamil[~a] = {0.}; ~%", numP),
  replaceList : [wvpar^2=wvparSq, rdvpar2^2=rdvpar2Sq, rdx2^2=rdx2Sq, m_^2=mSq, q_^2=qSq],
  hamilCvar : eval_string(sconcat("hamil")),
  writeCExprsNoExpand1(hamilCvar, gcfac(float(expand(subst(replaceList, hamil_c))))),
  printf(fh, "~%"),
  flush_output(fh),
  hamilNoZero_c : makelistNoZeros1(hamil_c, hamilCvar),
  /* Expand projected Hamiltonian on basis. */
  hamil_e : hamilNoZero_c . bP,

  /*Expand Jf*/
  Jf_e : doExpand1(fin,bP),

  /* Calculate expressions for dericatives of the hamiltonian*/
  vpardim : pdim-1,
  if vdim = 1 then ( vpardim : pdim ),
  dH_dvpar : diff(hamil_e,varsP[vpardim])/vmap_prime_e[1], /* We do not multply by rdv2vec because it is inside vmap_prime */
  if cdim = 3 then (
    dH_dx : diff(hamil_e*rdx2vec[xidx],varsP[xidx]),
    dH_dy : diff(hamil_e*rdx2vec[yidx],varsP[yidx]),
    dH_dz : diff(hamil_e*rdx2vec[zidx],varsP[zidx]),
    gradH_vec : [dH_dx, dH_dy, dH_dz, dH_dvpar]
  ) else if cdim = 2 then (
    dH_dx : diff(hamil_e*rdx2vec[xidx],varsP[xidx]),
    dH_dy : 0,
    dH_dz : diff(hamil_e*rdx2vec[zidx],varsP[zidx]),
    gradH_vec : [dH_dx, dH_dz, dH_dvpar]
  ) else if cdim = 1 then (
    dH_dx : 0,
    dH_dy : 0,
    dH_dz : diff(hamil_e*rdx2vec[zidx],varsP[zidx]),
    gradH_vec : [dH_dz, dH_dvpar]
  ),
  gradH_list : [dH_dx, dH_dy, dH_dz, dH_dvpar],

  if cdim = 3 then (
    bcrossgradH_x : bioverJB_y_e*dH_dz - bioverJB_z_e*dH_dy,
    bcrossgradH_y : bioverJB_z_e*dH_dx - bioverJB_x_e*dH_dz,
    bcrossgradH_z : bioverJB_x_e*dH_dy - bioverJB_y_e*dH_dx,
    bcrossgradH_vec : [bcrossgradH_x, bcrossgradH_y, bcrossgradH_z]
  ) else if cdim = 2 then (
    bcrossgradH_x : bioverJB_y_e * dH_dz,
    bcrossgradH_y : 0,
    bcrossgradH_z : -bioverJB_y_e * dH_dx,
    bcrossgradH_vec : [bcrossgradH_x, bcrossgradH_z]
  ) else if cdim = 1 then (
    bcrossgradH_x : 0,
    bcrossgradH_y : 0,
    bcrossgradH_z : 0,
    bcrossgradH_vec : [0]
  ),
  bcrossgradH_list : [bcrossgradH_x, bcrossgradH_y, bcrossgradH_z],

  /*Make sure to avoid having hamil[i]^2 or vmap[i]^2 in expressions*/
  replaceListVpar : [vmap[1]^2=vmap2],
  printf(fh, "  double vmap2 = vmap[1]*vmap[1]; ~%"),
  printf(fh, "~%"),

  mvpar_e : dH_dvpar,

  mvparsq_e : mvpar_e*mvpar_e/m_,
  isqlist : [],
  for i : 1 thru numP do (
    if freeof(hamil[i]^2, expand(mvparsq_e)) = false then (
      isqlist : append(isqlist,[i])
    )
  ),

  replaceListHamil : [],
  printf(fh, "  double hamil2[~a] = {0.}; ~%", length(isqlist)),
  for i : 1 thru length(isqlist) do (
    printf(fh, "  hamil2[~a] = hamil[~a]*hamil[~a]; ~%", i-1, isqlist[i], isqlist[i]),
    replaceListHamil : append(replaceListHamil, [hamil[isqlist[i]]^2=hamil2[i-1]])
  ),
  printf(fh, "~%"),

  /* Note: no contribution from mu. */
  for dir : 1 thru cdim+1 do (

    dirLabel : varLabel[dir],

    wDir      : eval_string(sconcat("w",dirLabel)),
    rdDirVar2 : eval_string(sconcat("rd",dirLabel,"2")),
  
    dirVar    : varsP[dir],         /* Variable in current direction. */

    if dir = cdim then (
      alpha_e : rtg33inv_e * dH_dvpar / m_ /* Contribution from B_0 . dH/dvpar . ∇ψ in z*/
    )
    else if dir = vpardim then (
      alpha_e : -rtg33inv_e * gradH_vec[zidx]/m_  /* Contribution from B_0 . ∇H . dψ/dvpar in z */
    )
    else (
      alpha_e : 0 /* all other B_0 contributions are 0 since B_0_x,y = 0 */
    ),

    if no_by = false then (

      /* Add curvature drift terms (m vpar/q * ∇ x b)/mB  = (m vpar * (∇ x b)/B)/qm */
      if dir < vpardim then (
        /* Config space contributions ( curv drift * dH/dvpar . ∇ψ ) */
        alpha_e : alpha_e + mvpar_e * dualcurlbhatoverB_vec[dir] * dH_dvpar / (q_*m_),
        /* Add b x ∇H / qB term (only in configuration space) */
        alpha_e : alpha_e + 1/q_ * bcrossgradH_vec[dir]
      ) else (
        /* Vpar contribution ( curv drift . ∇H * dψ/dvpar )*/
        for k : 1 thru cdim do (
          alpha_e : alpha_e - mvpar_e*dualcurlbhatoverB_vec[k]*gradH_vec[k]/(q_*m_)
        ) 
      )
    ),

    if dir < vpardim then (
      alpha_e : alpha_e*rdx2vec[dir]
    )
    else (
      alpha_e : alpha_e/vmap_prime_e[1]
    ),

    /* Project alpha on basis and write to array. */
    printf(fh, "  double alpha~a[~a] = {0.}; ~%", dirLabel, numP),
    alpha_c : fullratsimp(calcInnerProdList(varsP, 1, bP, alpha_e)),
    alpha_c : subst(replaceList, alpha_c),
    alpha_c : subst(replaceListHamil, alpha_c),
    alpha_c : subst(replaceListVpar, alpha_c),
    alpha_c : subst(dvparSimp, alpha_c),
    alphaLabel : eval_string(sconcat(alpha, dirLabel)),
    clst : [rdx2vec, rdv2vec, m_, q_, wvpar, rdvpar2Sq,
            makelist(dxv[i-1],i,1,pdim), makelist(vmap[i-1],i,1,2*length(vmap_e[1]))],
    writeCExprsCollect1(alphaLabel, alpha_c, clst),
    printf(fh, "~%"),
    flush_output(fh),
    alphaNoZero_c : makelistNoZeros1(alpha_c, alphaLabel),
    alpha_e       : doExpand(alphaNoZero_c, bP),

    alphaJf_e : alpha_e*Jf_e,

    printf(fh, "~%"),
    volTerm_c : fullratsimp(calcInnerProdList(varsP, 1, diff(bP,varsP[dir]), alphaJf_e)),
    volTerm_c : subst(replaceList, volTerm_c),
    writeCIncrExprsNoExpand(gcfac(float(expand(volTerm_c)))),
    flush_output(fh),
    printf(fh, "~%")

  ),

  printf(fh, "  return 0.; ~%"),
  printf(fh, "} ~%")

)$

addAparGKEMVolKernel(fh, funcNm, cdim, vdim, basisFun, polyOrder, varsInB, no_by) := block(
  [pdim,varsC,bC,varsP,bP,varsV,vSub,numC,numP,varLabel,d,rdx2vec,rdv2vec,allVarLabelsC,
   bmagBasis,ignoreVars,inFlds_e,cmag_e,b_x_e,b_y_e,b_z_e,jacobTotInv_e,vmap_e,BstardBmag_e,
   hamil_e,pbAuxFlds,alphaSum_e,vd,dir,dirLabel,wDir,rdDirVar2,vmap_prime_fac,dirVar,
   dirVar_phys,alpha_e,alpha_c,alphaLabel,alphaNoZero_c,alphaDotGradBasis_e,f_e,volTerm_c, dH_dz_e, alphaJf_e, Jf_e, 
   replaceListHamil, replaceListVpar,hamil2_c,isqlist,mvpar_e,mvparsq_e,dim_idx_list, xidx, yidx, zidx, vidx,
   replaceList,dvparSimp,phi_e,bmag_e,rtg33inv_e,bioverJB_x_e,bioverJB_y_e,bioverJB_z_e,bioverJB_list,
   dualcurlbhatoverB_x_e,dualcurlbhatoverB_y_e,dualcurlbhatoverB_z_e, dH_dx, dH_dy, dH_dz, dH_dvpar, gradH_vec,
   vmapSq_e,vmap_prime_e,hamil_c,hamilCvar,hamilNoZero_c,vpardim,i,k,Apar_e, dA_dx, dA_dy, dA_dz, gradA_vec,
   rotAbovermB_x,rotAbovermB_y,rotAbovermB_z,rotAbovermB_list, gradAxbhatoverB_x,gradAxbhatoverB_y,gradAxbhatoverB_z,gradAxbhatoverB_vec,
   curvdriftdir,clst],

  kill(varsC,varsP,bC,bP),
  pdim : cdim+vdim,

  [varsC,bC,varsP,bP,vSub] : loadGkBasis(basisFun, cdim, vdim, polyOrder),
  numC : length(bC),  numP : length(bP), 

  varLabel : makelist(string(varsP[d]),d,1,pdim),

  print("Working on ", funcNm),
  printf(fh, "GKYL_CU_DH double ~a(const double *w, const double *dxv, const double *vmap, const double *vmapSq,
    const double q_, const double m_, const double *bmag, const double *jacobtot_inv, const double *dualcurlbhatoverB, const double *bioverJB,
    const double *b_i, const double *phi, const double *apar, const double *fin, double* GKYL_RESTRICT out) ~%{ ~%", funcNm),
  printf(fh, "  // w[NDIM]: cell-center.~%"),
  printf(fh, "  // dxv[NDIM]: cell length.~%"),
  printf(fh, "  // vmap: velocity space mapping.~%"),
  printf(fh, "  // vmapSq: velocity space mapping squared.~%"),
  printf(fh, "  // q_,m_: species charge and mass.~%"),
  printf(fh, "  // bmag: magnetic field amplitude.~%"),
  printf(fh, "  // jacobtot_inv: reciprocal of the conf-space jacobian time the guiding center coordinate Jacobian.~%"),
  printf(fh, "  // dualcurlbhatoverB: dual curl of bhat over B.~%"),
  printf(fh, "  // bioverJB: b_i over J times B.~%"),
  printf(fh, "  // b_i: covariant components of the field aligned unit vector.~%"),
  printf(fh, "  // apar: parallel component of magnetic vector potential.~%"),
  printf(fh, "  // phi: electrostatic potential .~%"),
  printf(fh, "  // fin: Distribution function.~%"),
  printf(fh, "  // out: output increment.~%"),
  printf(fh, "~%"),

  /* Declare cell-center variables and variables multiplying gradients. */
  for d : 1 thru pdim do (
    printf(fh, "  double rd~a2 = 2.0/dxv[~a];~%", varLabel[d], d-1)
  ),
  printf(fh, "~%"),
  rdx2vec : makelist(eval_string(sconcat("rd",varLabel[i],"2")),i,1,cdim),
  rdv2vec : makelist(eval_string(sconcat("rd",varLabel[i],"2")),i,cdim+1,pdim),

  /* Declare variables with squared of cell centers and rdx2 variables (only need vpar^2). */
  /* printf(fh, "  double rdvpar2Sq = rdvpar2*rdvpar2;~%"), */
  /* printf(fh, "  double dvparSq = dxv[~a]*dxv[~a];~%", cdim, cdim), */
  printf(fh, "~%"),
  replaceList : [rdx^2=dx2Sq, rdy^2=dy2Sq, rdz^2=dx2Sq, rdvpar2^2=rdvpar2Sq,dxv[cdim]^2=dvparSq,rdvpar2Sq=4/dvparSq],
  dvparSimp : append(makelist(dxv[i-1]=2/eval_string(sconcat("rd",varLabel[i],"2")),i,1,pdim),
                     [dvparSq=4/rdvpar2Sq]),

  /* Store indices of the coordinate directions. */
  if cdim = 3 then (
    xidx : 1, yidx : 2, zidx : 3, vidx : 4
  ) else if cdim = 2 then (
    xidx : 1, zidx : 2, vidx : 3
  ) else if cdim = 1 then (
    zidx : 1, vidx : 2
  ),

  /* Create pointers to the components of b_i. */
  allVarLabelsC : ["x","y","z"],
  for d : 1 thru 3 do (
    printf(fh, "  const double *b_~a = &b_i[~a];~%", allVarLabelsC[d], numC*(d-1))
  ),
  printf(fh, "~%"),

  for d : 1 thru 3 do (
    printf(fh, "  const double *bioverJB_~a = &bioverJB[~a]; ~%", allVarLabelsC[d], numC*(d-1))
  ),
  printf(fh, "~%"),

  /* Create pointers to the components of dualcurlbhatoverB. */
  for d : 1 thru 3 do (
    printf(fh, "  const double *dualcurlbhatoverB_~a = &dualcurlbhatoverB[~a]; ~%", allVarLabelsC[d], numC*(d-1))
  ),
  printf(fh, "~%"),

  /* Axisymmetric basis (independent of y). */
  bmagBasis : getAxisymmetricConfBasis(bC),
  /* Expand input fields for Hamiltonian calculation */
  phi_e     : doExpand1(phi,bC),
  bmag_e : doExpand1(bmag, bmagBasis),
  rtg33inv_e : doExpand1(rtg33inv, bmagBasis),
  dualcurlbhatoverB_x_e : doExpand1(dualcurlbhatoverB_x, bmagBasis),
  dualcurlbhatoverB_y_e : doExpand1(dualcurlbhatoverB_y, bmagBasis),
  dualcurlbhatoverB_z_e : doExpand1(dualcurlbhatoverB_z, bmagBasis),
  bioverJB_x_e : doExpand1(bioverJB_x, bmagBasis),
  bioverJB_y_e : doExpand1(bioverJB_y, bmagBasis),
  bioverJB_z_e : doExpand1(bioverJB_z, bmagBasis),
  b_x_e : doExpand1(b_x, bmagBasis),
  b_y_e : doExpand1(b_y, bmagBasis),
  if (no_by or cdim = 1) then (b_y_e : 0),
  b_z_e : doExpand1(b_z, bmagBasis),
  jacobTotInv_e : doExpand1(jacobtot_inv, bmagBasis),

  dualcurlbhatoverB_list : [dualcurlbhatoverB_x_e, dualcurlbhatoverB_y_e, dualcurlbhatoverB_z_e],
  bioverJB_list : [bioverJB_x_e, bioverJB_y_e, bioverJB_z_e],
  if cdim = 3 then (
    dualcurlbhatoverB_vec : [dualcurlbhatoverB_x_e, dualcurlbhatoverB_y_e, dualcurlbhatoverB_z_e],
    bioverJB_vec : [bioverJB_x_e, bioverJB_y_e, bioverJB_z_e]
  ) else if cdim = 2 then (
    dualcurlbhatoverB_vec : [dualcurlbhatoverB_x_e, dualcurlbhatoverB_z_e],
    bioverJB_vec : [bioverJB_x_e, bioverJB_z_e]
  ) else if cdim = 1 then (
    dualcurlbhatoverB_vec : [dualcurlbhatoverB_z_e],
    bioverJB_vec : [bioverJB_z_e]
  ),

  /* Velocity mapping fields. */
  [vmap_e,vmapSq_e,vmap_prime_e] : expandVmapFields(varsP),

  /* Redefine vmap_prime to exploit the relationship between it and vmap. */
  vmap_prime_e : makelist(diff(vmap_e[d],varsP[cdim+d]),d,1,vdim),

  /* Write out the hamiltonian*/
  hamil_e : q_*phi_e + (1/2)*m_*vmapSq_e[1],
  if vdim > 1 then ( hamil_e : hamil_e + vmap_e[2]*bmag_e ),
  hamil_c : calcInnerProdList(varsP, 1, bP, hamil_e),
  printf(fh, "  double hamil[~a] = {0.}; ~%", numP),
  replaceList : [wvpar^2=wvparSq, rdvpar2^2=rdvpar2Sq, rdx2^2=rdx2Sq, rdy2^2=rdy2Sq, rdz2^2=rdz2Sq, m_^2=mSq, q_^2=qSq],
  hamilCvar : eval_string(sconcat("hamil")),
  writeCExprsNoExpand1(hamilCvar, gcfac(float(expand(subst(replaceList, hamil_c))))),
  printf(fh, "~%"),
  flush_output(fh),
  hamilNoZero_c : makelistNoZeros1(hamil_c, hamilCvar),
  /* Expand projected Hamiltonian on basis. */
  hamil_e : hamilNoZero_c . bP,

  /*Expand Jf*/
  Jf_e : doExpand1(fin,bP),

  /* Calculate expressions for dericatives of the hamiltonian*/
  vpardim : pdim-1,
  if vdim = 1 then ( vpardim : pdim ),
  dH_dz_e : makelist(0, i, 1, pdim),  
  for i : 1 thru vpardim do (
    if i = vpardim then (
      dH_dz_e[i] : diff(hamil_e,varsP[i])
    )
    else (
      dH_dz_e[i] : diff(hamil_e*rdx2vec[i],varsP[i])
    )
  ),
  dH_dvpar : diff(hamil_e,varsP[vpardim])/vmap_prime_e[1], /* We do not multply by rdv2vec because it is inside vmap_prime */
  if cdim = 3 then (
    dH_dx : diff(hamil_e*rdx2vec[xidx],varsP[xidx]),
    dH_dy : diff(hamil_e*rdx2vec[yidx],varsP[yidx]),
    dH_dz : diff(hamil_e*rdx2vec[zidx],varsP[zidx]),
    gradH_vec : [dH_dx, dH_dy, dH_dz, dH_dvpar]
  ) else if cdim = 2 then (
    dH_dx : diff(hamil_e*rdx2vec[xidx],varsP[xidx]),
    dH_dy : 0,
    dH_dz : diff(hamil_e*rdx2vec[zidx],varsP[zidx]),
    gradH_vec : [dH_dx, dH_dz, dH_dvpar]
  ) else if cdim = 1 then (
    dH_dx : 0,
    dH_dy : 0,
    dH_dz : diff(hamil_e*rdx2vec[zidx],varsP[zidx]),
    gradH_vec : [dH_dz, dH_dvpar]
  ),

  /*Make sure to avoid having hamil[i]^2 or vmap[i]^2 in expressions*/
  replaceListVpar : [vmap[1]^2=vmap2],
  printf(fh, "  double vmap2 = vmap[1]*vmap[1]; ~%"),
  printf(fh, "~%"),

  mvpar_e : dH_dvpar,
  mvparsq_e : mvpar_e*mvpar_e/m_,
  isqlist : [],
  for i : 1 thru numP do (
    if freeof(hamil[i]^2, expand(mvparsq_e)) = false then (
      isqlist : append(isqlist,[i])
    )
  ),

  replaceListHamil : [],
  printf(fh, "  double hamil2[~a] = {0.}; ~%", length(isqlist)),
  for i : 1 thru length(isqlist) do (
    printf(fh, "  hamil2[~a] = hamil[~a]*hamil[~a]; ~%", i-1, isqlist[i], isqlist[i]),
    replaceListHamil : append(replaceListHamil, [hamil[isqlist[i]]^2=hamil2[i-1]])
  ),
  printf(fh, "~%"),

  /* Expand Apar.*/
  /* Apar_e : subst(y=0, doExpand1(apar,bC)), */
  Apar_e : doExpand1(apar,bC),

  /* Expand dBperp/Bmag. */
  /* Direct method ∇ x (Apar bhat) */
  rotAbovermB_x : (rdy2*diff(Apar_e*b_z_e,y) - rdz2*diff(Apar_e*b_y_e,z))*jacobTotInv_e/m_,
  rotAbovermB_y : (rdz2*diff(Apar_e*b_x_e,z) - rdx2*diff(Apar_e*b_z_e,x))*jacobTotInv_e/m_,
  rotAbovermB_z : (rdx2*diff(Apar_e*b_y_e,x) - rdy2*diff(Apar_e*b_x_e,y))*jacobTotInv_e/m_,
  rotAbovermB_list : [rotAbovermB_x, rotAbovermB_y, rotAbovermB_z],

  /* Product rule method Apar ∇ x bhat + ∇Apar x bhat. */
  /* Calculate ∇Apar in a list */
  if cdim = 3 then (
    dA_dx : diff(Apar_e*rdx2vec[xidx],varsC[xidx]),
    dA_dy : diff(Apar_e*rdx2vec[yidx],varsC[yidx]),
    dA_dz : diff(Apar_e*rdx2vec[zidx],varsC[zidx]),
    gradA_vec : [dA_dx, dA_dy, dA_dz]
  ) else if cdim = 2 then (
    dA_dx : diff(Apar_e*rdx2vec[xidx],varsC[xidx]),
    dA_dy : 0,
    dA_dz : diff(Apar_e*rdx2vec[zidx],varsC[zidx]),
    gradA_vec : [dA_dx, dA_dz]
  ) else if cdim = 1 then (
    dA_dx : 0,
    dA_dy : 0,
    dA_dz : diff(Apar_e*rdx2vec[zidx],varsC[zidx]),
    gradA_vec : [dA_dz]
  ),

  /* Use bioverJB to calculate ∇Apar x b / B in a list */
  if cdim = 3 then (
    gradAxbhatoverB_x : gradA_vec[yidx]*bioverJB_list[3] - gradA_vec[zidx]*bioverJB_list[2],
    gradAxbhatoverB_y : gradA_vec[zidx]*bioverJB_list[1] - gradA_vec[xidx]*bioverJB_list[3],
    gradAxbhatoverB_z : gradA_vec[xidx]*bioverJB_list[2] - gradA_vec[yidx]*bioverJB_list[1],
    gradAxbhatoverB_vec : [gradAxbhatoverB_x, gradAxbhatoverB_y, gradAxbhatoverB_z]
  ) else if cdim = 2 then (
    gradAxbhatoverB_x : -gradA_vec[zidx]*bioverJB_list[2],
    gradAxbhatoverB_y : 0,
    gradAxbhatoverB_z : +gradA_vec[xidx]*bioverJB_list[2],
    gradAxbhatoverB_vec : [gradAxbhatoverB_x, gradAxbhatoverB_z]
  ) else if cdim = 1 then (
    gradAxbhatoverB_x : 0,
    gradAxbhatoverB_y : 0,
    gradAxbhatoverB_z : 0,
    gradAxbhatoverB_vec : [gradAxbhatoverB_z]
  ),

  dim_idx_list : [3, 1, 2],
  
  /* Note: no contribution from mu. */
  for dir : 1 thru cdim+1 do (

    dirLabel : varLabel[dir],

    wDir      : eval_string(sconcat("w",dirLabel)),
    rdDirVar2 : eval_string(sconcat("rd",dirLabel,"2")),
  
    dirVar    : varsP[dir],         /* Variable in current direction. */

    alpha_e : 0,

    if no_by = false then (
      if dir < vpardim then ( /* Config space contributions ( curv drift * dH/dvpar . ∇ψ ) */
        /* This is [Apar . (∇ x b)/B + ∇Apar x b/B]/m dH/dvpar . ∇ψ */
        alpha_e : alpha_e + 1/m_ * Apar_e * dualcurlbhatoverB_vec[dir] * dH_dvpar,
        /* This term is responsible of y oscillations in the Alfven 3x2v regression test. */
        /* The oscillation builds up at longer time (not observable at frame 1). */
        alpha_e : alpha_e + 1/m_ * gradAxbhatoverB_vec[dir] * dH_dvpar
      ) else ( /* Vpar contribution ( curv drift . ∇H * dψ/dvpar )*/
        for k : 1 thru cdim do (
          /* this is [Apar . (∇ x b)/B]/m . ∇H * dψ/dvpar */
          alpha_e : alpha_e - 1/m_ * (Apar_e * dualcurlbhatoverB_vec[k]) * gradH_vec[k],
          /* this is [∇Apar x b/B]/m . ∇H * dψ/dvpar */
          alpha_e : alpha_e - 1/m_ * gradAxbhatoverB_vec[k] * gradH_vec[k]
        )
      )
    ),

    if dir < vpardim then (
      alpha_e : alpha_e*rdx2vec[dir]
    )
    else (
      alpha_e : alpha_e/vmap_prime_e[1]
    ),

    /* Project alpha on basis and write to array. */
    printf(fh, "  double alpha~a[~a] = {0.}; ~%", dirLabel, numP),
    alpha_c : fullratsimp(calcInnerProdList(varsP, 1, bP, alpha_e)),
    alpha_c : subst(replaceList, alpha_c),
    alpha_c : subst(replaceListHamil, alpha_c),
    alpha_c : subst(replaceListVpar, alpha_c),
    alpha_c : subst(dvparSimp, alpha_c),
    alphaLabel : eval_string(sconcat(alpha, dirLabel)),
    clst : [rdx2vec, rdv2vec, m_, q_, wvpar, rdvpar2Sq,
            makelist(dxv[i-1],i,1,pdim), makelist(vmap[i-1],i,1,2*length(vmap_e[1]))],
    writeCExprsCollect1(alphaLabel, alpha_c, clst),
    printf(fh, "~%"),
    flush_output(fh),
    alphaNoZero_c : makelistNoZeros1(alpha_c, alphaLabel),
    alpha_e       : doExpand(alphaNoZero_c, bP),

    alphaJf_e : alpha_e*Jf_e,

    printf(fh, "~%"),
    volTerm_c : fullratsimp(calcInnerProdList(varsP, 1, diff(bP,varsP[dir]), alphaJf_e)),
    volTerm_c : subst(replaceList, volTerm_c),
    writeCIncrExprsNoExpand(gcfac(float(expand(volTerm_c)))),
    flush_output(fh),
    printf(fh, "~%")

  ),

  printf(fh, "  return 0.; ~%"),
  printf(fh, "} ~%")

)$

addApardotGKEMVolKernel(fh, funcNm, cdim, vdim, basisFun, polyOrder, varsInB, no_by) := block(
  [pdim,varsC,bC,varsP,bP,varsV,vSub,numC,numP,varLabel,d,rdx2vec,rdv2vec,allVarLabelsC,
   bmagBasis,ignoreVars,inFlds_e,cmag_e,b_x_e,b_y_e,b_z_e,jacobTotInv_e,vmap_e,BstardBmag_e,
   hamil_e,pbAuxFlds,alphaSum_e,vd,vpardir,dirLabel,wDir,rdDirVar2,vmap_prime_fac,dirVar,
   dirVar_phys,alpha_e,alpha_c,alphaLabel,alphaNoZero_c,alphaDotGradBasis_e,f_e,volTerm_c, dH_dz_e, 
   alphaJf_e, Jf_e, replaceListHamil, replaceListVpar,hamil2_c,isqlist,mvpar_e,mvparsq_e,
   vmapSq_e,vmap_prime_e,apardot_e,clst],

  kill(varsC,varsP,bC,bP),
  pdim : cdim+vdim,

  [varsC,bC,varsP,bP,vSub] : loadGkBasis(basisFun, cdim, vdim, polyOrder),
  numC : length(bC),  numP : length(bP), 

  varLabel : makelist(string(varsP[d]),d,1,pdim),

  print("Working on ", funcNm),
  printf(fh, "GKYL_CU_DH double ~a(const double *vmap, const double q_, const double m_, const double *apardot,
    const double *fin, double* GKYL_RESTRICT out) ~%{ ~%", funcNm),
  printf(fh, "  // q_,m_: species charge and mass.~%"),
  printf(fh, "  // apardot: time derivative of parallel component of magnetic vector potential.~%"),
  printf(fh, "  // fin: Distribution function.~%"),
  printf(fh, "  // out: output increment.~%"),
  printf(fh, "~%"),

  rdx2vec : makelist(eval_string(sconcat("rd",varLabel[i],"2")),i,1,cdim),
  rdv2vec : makelist(eval_string(sconcat("rd",varLabel[i],"2")),i,cdim+1,pdim),


  /* Velocity mapping fields. */
  [vmap_e,vmapSq_e,vmap_prime_e] : expandVmapFields(varsP),
  vmap_prime_e : makelist(diff(vmap_e[d],varsP[cdim+d]),d,1,vdim),

  /*Expand Jf*/
  Jf_e : doExpand1(fin,bP),

  /* Expand Apardot */
  apardot_e : doExpand1(apardot,bC),

  /* Note: only a vpar contribution. */
  vpardir : cdim+1,
  dirLabel : varLabel[vpardir],

  alpha_e : -q_/m_ * apardot_e /vmap_prime_e[1],

  /* Project alpha on basis and write to array. */
  printf(fh, "  double alpha~a[~a] = {0.}; ~%", dirLabel, numP),
  alpha_c : fullratsimp(calcInnerProdList(varsP, 1, bP, alpha_e)),
  alphaLabel : eval_string(sconcat(alpha, dirLabel)),
  clst : [rdx2vec, rdv2vec, m_, q_, wvpar, rdvpar2Sq,
          makelist(dxv[i-1],i,1,pdim), makelist(vmap[i-1],i,1,2*length(vmap_e[1]))],
  writeCExprsCollect1(alphaLabel, alpha_c, clst),
  printf(fh, "~%"),
  flush_output(fh),
  alphaNoZero_c : makelistNoZeros1(alpha_c, alphaLabel),
  alpha_e       : doExpand(alphaNoZero_c, bP),

  alphaJf_e : alpha_e*Jf_e,

  printf(fh, "~%"),
  volTerm_c : fullratsimp(calcInnerProdList(varsP, 1, diff(bP,varsP[vpardir]), alphaJf_e)),
  writeCIncrExprsNoExpand(gcfac(float(expand(volTerm_c)))),
  flush_output(fh),
  printf(fh, "~%"),

  printf(fh, "  return 0.; ~%"),
  printf(fh, "} ~%")

)$