/* Functions (called by gyrokineticIntmoment.mac) that compute the
   integrated moments of the distribution function in gyrokinetic model. */

load("modal-basis");
load("out-scripts");
load(stringproc)$
fpprec : 24$

volExpr(totDim) := prod(dxv[i-1], i, 1, totDim)$

expandVmapFields(varsP) := block(
  /* Expand the fields used for the velocity mapping. */
  [pDim,vdim,cdim,jnk,vmapBasis,vmapSqBasis,vmapBnum,vmapSqBnum,
   vmap_e,vmapSq_e,vmap_prim_e,d,vmap_c,vmapSq_c],

  pDim : length(varsP),
  vdim : 1,
  if isInList(mu,varsP) then vdim : 2,
  cdim : pDim-vdim,

  /* Basis for the velocity space mapping. */
  [jnk,vmapBasis] : loadBasis("Ser", 1, 1),  [jnk,vmapSqBasis] : loadBasis("Ser", 1, 2),
  vmapBnum        : length(vmapBasis),       vmapSqBnum        : length(vmapSqBasis),

  vmap_e : [],  vmapSq_e : [],  vmap_prime_e : [],
  for d : 1 thru vdim do (
    vmap_c : makelist(vmap[(d-1)*vmapBnum+i-1],i,1,vmapBnum),
    vmap_e : endcons(doExpand(vmap_c,subst(x=varsP[cdim+d],vmapBasis)), vmap_e),

    vmapSq_c : makelist(vmapSq[(d-1)*vmapSqBnum+i-1],i,1,vmapSqBnum),
    vmapSq_e : endcons(doExpand(vmapSq_c,subst(x=varsP[cdim+d],vmapSqBasis)), vmapSq_e),

    vmap_prime_e : endcons(vmap_prime[d-1], vmap_prime_e)
  ),

  return([vmap_e,vmapSq_e,vmap_prime_e])
)$

calcIntMDist(fh, funcNm, cdim, vdim, basisFun, polyOrder) := block(
  [varsC,bC,varsP,bP,vSub,vmap_e,vmapSq_e,vmap_prime_e,vmap_c,
   d,f_e,M,m0,m1,m2par,bmag_e,Mtepm,tmp_e,m2perp,tempPowVars],

  [varsC,bC,varsP,bP,vSub] : loadGkBasis(basisFun, cdim, vdim, polyOrder),

  [vmap_e,vmapSq_e,vmap_prime_e] : expandVmapFields(varsP),

  vmap_c : [],
  for d : 1 thru vdim do (
    vmap_c : append( vmap_c, delete(mu,delete(vpar,listofvars(vmap_e[d]))) )
  ),
  
  printf(fh, "GKYL_CU_DH void ~a_~ax~av_~a_p~a(const double *dxv, const double *vmap, double m_, const double *bmag, const double *f, double* GKYL_RESTRICT out) ~%{ ~%", funcNm, cdim, vdim, basisFun, polyOrder),

  if vdim = 1 then printf(fh, "  const double volFact = ~a; ~%", volExpr(cdim+vdim)*float(1/(2^(cdim+vdim))) )
  else printf(fh, "  const double volFact = M_PI/m_*~a; ~%", 2*volExpr(cdim+vdim)*float(1/(2^(cdim+vdim))) ),

  printf(fh, " ~%"),

  f_e : doExpand1(f, bP),

  M : [],

  /* Integrated M0. */
  m0 : fullratsimp(innerProd(varsP, 1, 1, f_e)),
  M  : endcons(m0,M),

  /* Integrated parallel momentum (M0 upar). */
  m1 : fullratsimp(innerProd(varsP, 1, vmap_e[1], f_e)),
  M  : endcons(m1,M),

  /* Integrated parallel particle energy (M2par). */
  m2par : fullratsimp(innerProd(varsP, 1, (vmap_e[1])^2, f_e)),
  M  : endcons(m2par, M),

  if (vdim > 1) then (
    bmag_e : doExpand1(bmag, bC),

    Mtemp : calcInnerProdList(varsP, vmap_e[2], bC, f_e),
    Mtemp : map(letsimp, Mtemp),

    printf(fh, "  double tmp[~a]; ~%", length(bC)),

    writeCExprs1(tmp, 2/m_*Mtemp),
    printf(fh, " ~%"),
    tmp_e : doExpand1(tmp, bC),

    m2perp : fullratsimp(innerProd(varsC, 1, bmag_e, tmp_e)),
    M  : endcons(m2perp, M)
  ),

  M : map(letsimp, M),

  tempPowVars : [],
  tempPowVars : writeCIncrExprsCollect1noPowers(out, volFact*M, [volFact], [vmap_c], tempPowVars),


  printf(fh, "} ~%")
)$

calcIntMoments(fh, funcNm, cdim, vdim, basisFun, polyOrder) := block([],
  printf(fh, "#include <gkyl_mom_gyrokinetic_kernels.h> ~%"),
  calcIntMDist(fh, funcNm, cdim, vdim, basisFun, polyOrder)
)$
