/* Generate the header file for the Vlasov moment and integrated moment kernels. */

/* ...... USER INPUTS........ */

/* Serendipity basis. */
minPolyOrder_Ser : 1$
maxPolyOrder_Ser : 2$
minCdim_Ser : 1$
maxCdim_Ser : 3$

/* Tensor product basis. */
/* Note that Serendipity, p = 1, is equivalent to Tensor */
/* Thus no need to calculate p = 1 Tensor basis */
minPolyOrder_Tensor : 2$
maxPolyOrder_Tensor : 2$
minCdim_Tensor : 1$
maxCdim_Tensor : 3$

/* Vdim possibilities for each of Cdim=[1,2,3]. */
gkVdims : [[1,2], [2], [2]]$

/* ...... END OF USER INPUTS........ */

/* To generate other bases, just add corresponding column to arrays below. */
bName        : ["ser", "tensor"]$
minPolyOrder : [minPolyOrder_Ser, minPolyOrder_Tensor]$
maxPolyOrder : [maxPolyOrder_Ser, maxPolyOrder_Tensor]$
minCdim      : [minCdim_Ser, minCdim_Tensor]$
maxCdim      : [maxCdim_Ser, maxCdim_Tensor]$

printPrototype(deco, ci, vi, bStr, pi) := block([si],
  printf(fh, "~avoid gyrokinetic_M0_~ax~av_~a_p~a(const double *w, const double *dxv, const int *idx, double m_, const double *bmag, const double *f, double* GKYL_RESTRICT out); ~%", deco, ci, vi, bStr, pi),
  printf(fh, "~avoid gyrokinetic_M1_~ax~av_~a_p~a(const double *w, const double *dxv, const int *idx, double m_, const double *bmag, const double *f, double* GKYL_RESTRICT out); ~%", deco, ci, vi, bStr, pi),
  printf(fh, "~avoid gyrokinetic_M2_par_~ax~av_~a_p~a(const double *w, const double *dxv, const int *idx, double m_, const double *bmag, const double *f, double* GKYL_RESTRICT out); ~%", deco, ci, vi, bStr, pi),
  if vi > 1 then printf(fh, "~avoid gyrokinetic_M2_perp_~ax~av_~a_p~a(const double *w, const double *dxv, const int *idx, double m_, const double *bmag, const double *f, double* GKYL_RESTRICT out); ~%", deco, ci, vi, bStr, pi),
  printf(fh, "~avoid gyrokinetic_M2_~ax~av_~a_p~a(const double *w, const double *dxv, const int *idx, double m_, const double *bmag, const double *f, double* GKYL_RESTRICT out); ~%", deco, ci, vi, bStr, pi),
  printf(fh, "~avoid gyrokinetic_M3_par_~ax~av_~a_p~a(const double *w, const double *dxv, const int *idx, double m_, const double *bmag, const double *f, double* GKYL_RESTRICT out); ~%", deco, ci, vi, bStr, pi),
  if vi > 1 then printf(fh, "~avoid gyrokinetic_M3_perp_~ax~av_~a_p~a(const double *w, const double *dxv, const int *idx, double m_, const double *bmag, const double *f, double* GKYL_RESTRICT out); ~%", deco, ci, vi, bStr, pi),
  printf(fh, "~avoid gyrokinetic_three_moments_~ax~av_~a_p~a(const double *w, const double *dxv, const int *idx, double m_, const double *bmag, const double *f, double* GKYL_RESTRICT out); ~%", deco, ci, vi, bStr, pi),
  if vi > 1 then (
    printf(fh, "~avoid gyrokinetic_M0_step1_~ax~av_~a_p~a(const double *w, const double *dxv, const int *idx, double m_, const double *bmag, const double *f, double* GKYL_RESTRICT out); ~%", deco, ci, vi, bStr, pi),
    printf(fh, "~avoid gyrokinetic_M0_step2_~ax~av_~a_p~a(const double *w, const double *dxv, const int *idx, double m_, const double *bmag, const double *f, double* GKYL_RESTRICT out); ~%", deco, ci, vi, bStr, pi)
  ),
  printf(fh, "~avoid gyrokinetic_int_mom_~ax~av_~a_p~a(const double *w, const double *dxv, const int *idx, double m_, const double *bmag, const double *f, double* GKYL_RESTRICT out); ~%", deco, ci, vi, bStr, pi),
  printf(fh, "~%") 
)$

fh : openw("~/max-out/gkyl_mom_gyrokinetic_kernels.h")$
printf(fh, "#pragma once ~%")$
printf(fh, "#include <math.h> ~%")$
printf(fh, "#include <gkyl_util.h> ~%")$
printf(fh, "EXTERN_C_BEG ~%")$
printf(fh, "~%")$

decorator : "GKYL_CU_DH "$
for bInd : 1 thru length(bName) do (
  for c : minCdim[bInd] thru maxCdim[bInd] do (
    for gkV : 1 thru length(gkVdims[c]) do (
      v : gkVdims[c][gkV],

      minPolyOrderB : minPolyOrder[bInd],
      maxPolyOrderB : maxPolyOrder[bInd],
      if (c+v>4 and maxPolyOrderB > 2) then maxPolyOrderB : 2,

      for polyOrder : minPolyOrderB thru maxPolyOrderB do (
        printPrototype(decorator, c, v, bName[bInd], polyOrder)
      )
    )
  )
);
printf(fh, "EXTERN_C_END ~%")$
close(fh)$
/* ............ Finished writing out the C header file ............ */
