/* Generate kernels for updater averaging a gkyl_array in given dimensions .*/

load("array_average/array_average")$

/* ...... USER INPUTS........ */

/* Serendipity basis. */
polyOrder : 1$
basisType : "ser"$
/* Out file names */
cfname : "~/max-out/array_average_kernels.c"$
hfname : "~/max-out/gkyl_array_average_kernels.h"$

/* ...... END OF USER INPUTS........ */

array_average(polyOrder,basisType,cfname,hfname)$