kill(all) $
load("/home/cagas65/gkeyll/gkylcas/maxima/g2/discontGenPoisson-calc/func_discont_gen_poisson_2D");


C : 0 $
basisLst : ["Ser", "Tensor"] $

for xi : -1 thru 1 do (
  for yi : -1 thru 1 do (
    isTopSkin : false,
    isBottomSkin : false,
    isLeftSkin : false,
    isRightSkin : false,
    if xi = -1 then
      isBottomSkin : true
    elseif xi = 1 then
      isTopSkin : true,
    if yi = -1 then
      isLeftSkin : true
    elseif yi = 1 then
      isRightSkin : true,

    for polyOrder : 1 thru 2 do (
      for bIdx : 1 thru min(length(basisLst),polyOrder) do (
        basis : basisLst[bIdx],

        for iRec6 : 0 thru 1 do (
          for iRecVol : 0 thru 1 do (
            for iRecD : 0 thru 1 do (
              useRec6 : if iRec6 = 0 then false else true,
              useRecVol : if iRecVol = 0 then false else true,
              useRecD : if iRecD = 0 then false else true,

              if useRec6 then (
                if useRecVol then (
                  if useRecD then
                    schemeNm : "II6d"
                  else
                    schemeNm : "II6"
                ) else (
                  if useRecD then
                    schemeNm : "I6d"
                  else
                    schemeNm : "I6"
                )
              ) else (
                if useRecVol then (
                  if useRecD then
                    schemeNm : "II2d"
                  else
                    schemeNm : "II2"
                ) else (
                  if useRecD then
                    schemeNm : "I2d"
                  else
                    schemeNm : "I2"
                )
              ),

              fileName : sconcat("~/max-out/dg_gen_poisson_",
                schemeNm, "_",
                sdowncase(basis), "_2x",
                if isTopSkin then "_T" else "",
                if isBottomSkin then "_B" else "",
                if isRightSkin then "_R" else "",
                if isLeftSkin then "_L" else "",
                "_p", polyOrder, ".lua"),

              stencil(basis, polyOrder, fileName, useRec6, useRecVol, useRecD, isTopSkin, isBottomSkin, isLeftSkin, isRightSkin, C)
            )
          )
        )
      )
    )
  )
)