/*
  Generate the volume kernels for electromagnetic (with Apar)
  gyrokinetics with general geometry.

  The functions called in this file are in gkFuncs-vol.mac.
*/
load("gyrokinetic/gkFuncs-vol")$

/* ...... USER INPUTS........ */

/* Serendipity basis. */
maxPolyOrder_Ser : 2$
minCdim_Ser : 1$
maxCdim_Ser : 1$

/* Tensor order basis. */
maxPolyOrder_Tensor : 2$
minCdim_Tensor : 1$
maxCdim_Tensor : 1$

/* Vdim possibilities for each of Cdim=[1,2,3]. */
gkVdims : [[1,2], [2], [2]]$

/* ...... END OF USER INPUTS........ */

/* To generate other bases, just add corresponding column to arrays below. */
bName        : ["ser", "tensor"]$
maxPolyOrder : [maxPolyOrder_Ser, maxPolyOrder_Tensor]$
minCdim      : [minCdim_Ser, minCdim_Tensor]$
maxCdim      : [maxCdim_Ser, maxCdim_Tensor]$

/* Possible combinations of variable dependence of background magnetic field.
   with [] = const. Note that we assume axisymmetry, which means B cannot depend on y. */
bVarsList : [x,z]$

/* Generate kernels of selected types. */
for bInd : 1 thru length(bName) do (
  for c : minCdim[bInd] thru maxCdim[bInd] do (
    for gkV : 1 thru length(gkVdims[c]) do (
      v : gkVdims[c][gkV],

      maxPolyOrderB : maxPolyOrder[bInd],
      if (c+v>4 and maxPolyOrderB > 2) then maxPolyOrderB : 1,

      for polyOrder : 1 thru maxPolyOrderB do (

        fname : sconcat("~/max-out/gyrokinetic_vol_", c, "x", v, "v_", bName[bInd], "_p", polyOrder, ".c"),
        disp(printf(false,"Creating volume file: ~a",fname)),
  
        fh : openw(fname),
        printf(fh, "#include <gkyl_gyrokinetic_kernels.h> ~%"),

        funcName : sconcat("gyrokinetic_vol_", c, "x", v, "v_", bName[bInd], "_p", polyOrder),
        buildGKVolKernel(fh, funcName, c, v, bName[bInd], polyOrder, bVarsList),

        /* Generate the kernel for the second step of GK with Apar. */
        funcName : sconcat("gyrokinetic_vol_step2_", c, "x", v, "v_", bName[bInd], "_p", polyOrder),
        buildGKStep2VolKernel(fh, funcName, c, v, bName[bInd], polyOrder),
        close(fh)
      )
    )
  )
)$
