/* Functions which compute the components of the surface flux in velocity space. 
   The procedure we utilize to generalize to the presence of different forces/different
   flavors of the Vlasov equation is a set of functions that compute the characteristics
   alpha_v at surface quadrature points of the needed order, accumulating each component, 
   e.g., Hamiltonian forces, the Lorentz force, or forces due to a scalar potential, 
   into a total alpha_v at the surface. 

   We then evaluate the Lax-Friedrichs flux G = alpha/2*(f^+ + f^-) - |alpha|/2*(f^+ - f^-)
   at each quadrature point, and then convert that back to a modal expansion of the 
   velocity-space flux for use in the final update in hyper_dg. 

   Note that we do not make any assumptions on the order of the phase space expansion
   and thus to evaluate G, we must utilize enough Gauss-Legendre quadrature points
   to integrate a 3*p polynomial (cubic for p=1, sixth order for p=2, ninth order for p=3). 
   We thus must use 2, 4, and 5 Gauss-Legendre points respectively. 

   In velocity space, certain Hamiltonians such as H = v^2/2 require fewer velocity space
   quadrature points since these Hamiltonians are "sparse." We separate the velocity space
   vs. configuration space quadrature loops and generate separate nodal configuration space
   and nodal velocity space surface bases. Since these quadrature rules are all tensor products
   of configuration space and velocity space, the final phase space basis is simply a tensor
   product of the configuration space and velocity space bases.  
*/

load("modal-basis");
load("out-scripts");
load("utilities")$
load("nodal_operations/nodal_functions")$
load("new_vlasov/vlasov-basis");
load(stringproc)$
fpprec : 24$

clabels : ["x","y","z"]$
dx1_inv : [dx10, dx11, dx12]$
dv1_inv : [dv10, dv11, dv12]$
vTrans  : [vx*dv0/2+wx1, vy*dv1/2+wx2, vz*dv2/2+wx3]$
cidx(cdim) := makelist(i,i,0,cdim-1)$
vidx(cdim,vdim) := makelist(i,i,cdim,cdim+vdim-1)$

/* Phase-space Hamiltonian forces at velocity-space surface quadrature points. */
calcHamilGenVelSurfForceNonCanonical(dir, fh, funcNm, cdim, vdim, basisFun, polyOrder, vel_hamil, useHigherOrder) := block(
  [varsC,bC,varsV,bV,varsP,bP,cid,hamil,vv,surfVars,surfVVars,bSurf,NSurf,
   nodes_conf,basisNodalConf,num_nodes_conf,nodes_vel,basisNodalVel,num_nodes_vel,
   surfNodes,numNodes,PI_dH_dz_l,pt_comp,conf_node,pt_index],

  [varsC,bC,varsV,bV,varsP,bP] : loadVlasovBasis(basisFun, cdim, vdim, polyOrder), 
  NC : length(bC), 

  printf(fh, "#include <gkyl_vlasov_kernels.h> ~%"),
  printf(fh, "GKYL_CU_DH void ~a(const double *w, const double *dxv, const double *pt_conf_nodal,
  const double *hamil, double* GKYL_RESTRICT alpha_quad) ~%{ ~%", funcNm),

  printf(fh, "~%"),
  if (vel_hamil) then (
    hamil : doExpand1(hamil, bV)
  )
  else (
    hamil : doExpand1(hamil, bP)    
  ),

  /* Save enough names for 3D (conf and vel spaces)*/
  ptConfNodal : [pt_conf_nodal_0, pt_conf_nodal_1, pt_conf_nodal_2,
    pt_conf_nodal_3, pt_conf_nodal_4, pt_conf_nodal_5, pt_conf_nodal_6,
    pt_conf_nodal_7, pt_conf_nodal_8],
  ptConfNodalx : [pt_conf_nodal_x0, pt_conf_nodal_x1, pt_conf_nodal_x2,
    pt_conf_nodal_x3, pt_conf_nodal_x4, pt_conf_nodal_x5, pt_conf_nodal_x6,
    pt_conf_nodal_x7, pt_conf_nodal_x8],

  vv : varsV[dir], 
  surfVars : delete(vv,varsP), /* Surface variables at constant vv surface. */
  surfVVars : delete(vv,varsV), /* Remaining variables in v. */
  [bSurf,nodes_conf,basisNodalConf,nodes_vel,basisNodalVel,surfNodes] : loadVlasovVelSurfBasis(cdim, vdim, basisFun, polyOrder, surfVars, surfVVars, varsC, useHigherOrder),
  NSurf : length(bSurf), 
  num_nodes_conf : length(nodes_conf), 
  num_nodes_vel : length(nodes_vel), 
  numNodes : length(surfNodes), 

  /* Create a projection of the momentum */
  vid : vidx(cdim,vdim), 
  for i : 1 thru vdim do printf(fh, "  const double wx~a = w[~a]; ~%", i, cdim+i-1, i, cdim+i-1),
  for i : 1 thru vdim do printf(fh, "  const double dv~a = dxv[~a]; ~%", i-1, vid[i]),
  if not(vel_hamil) then (
    for i : 1 thru cdim do printf(fh, "  const double dx1~a = 2.0/dxv[~a]; ~%", i-1, i-1)
  ),
  for i : 1 thru vdim do printf(fh, "  const double dv1~a = 2.0/dxv[~a]; ~%", i-1, vid[i]),

  /* Compute the characteristic for the NC Poisson Tensor */
  pt_comp : vdim*vdim,
  if not(vel_hamil) then (
    for i : 1 thru pt_comp do (
      printf(fh, "  const double *pt_conf_nodal_x~a = &pt_conf_nodal[~a]; ~%", i-1, num_nodes_conf*(i-1))
    )
  ),
  if (vdim > 1) then (
    for i : 1 thru pt_comp do (
      printf(fh, "  const double *pt_conf_nodal_~a = &pt_conf_nodal[~a]; ~%", i-1, num_nodes_conf*(pt_comp+i-1))
    )
  ),
  for i : 1 thru numNodes do (
    conf_node : floor((i-1)/num_nodes_vel),
    Pi_dH_dz : 0,
    if not(vel_hamil) then (
      for j : 1 thru cdim do (
        pt_index : (j-1)*vdim + (dir-1),
        PI_dH_dz_l : float(evAtNodes(subst(vv=-1,diff(hamil, varsC[j])*dx1_inv[j]),[surfNodes[i]],surfVars)),
        Pi_dH_dz : Pi_dH_dz - ptConfNodalx[pt_index+1][conf_node]*PI_dH_dz_l[1]
      )
    ),
    if (vdim = 2) then (
      omega_12 : float(evAtNodes(subst(vv=-1,vTrans[1]),[surfNodes[i]],surfVars))[1]*ptConfNodal[1][conf_node] + float(evAtNodes(subst(vv=-1,vTrans[2]),[surfNodes[i]],surfVars))[1]*ptConfNodal[2][conf_node],
      if (dir = 1) then (
        PI_dH_dz_l : float(evAtNodes(subst(vv=-1,diff(hamil,varsV[2])*dv1_inv[2]),[surfNodes[i]],surfVars)),
        Pi_dH_dz : Pi_dH_dz + omega_12*PI_dH_dz_l[1]
      )
      else if (dir = 2) then (
        PI_dH_dz_l : float(evAtNodes(subst(vv=-1,diff(hamil,varsV[1])*dv1_inv[1]),[surfNodes[i]],surfVars)),
        Pi_dH_dz : Pi_dH_dz - omega_12*PI_dH_dz_l[1]
      )
    ),
    if (vdim = 3) then (
      omega_12 : float(evAtNodes(subst(vv=-1,vTrans[1]),[surfNodes[i]],surfVars))[1]*ptConfNodal[1][conf_node] + float(evAtNodes(subst(vv=-1,vTrans[2]),[surfNodes[i]],surfVars))[1]*ptConfNodal[4][conf_node] + float(evAtNodes(subst(vv=-1,vTrans[3]),[surfNodes[i]],surfVars))[1]*ptConfNodal[7][conf_node],
      omega_13 : float(evAtNodes(subst(vv=-1,vTrans[1]),[surfNodes[i]],surfVars))[1]*ptConfNodal[2][conf_node] + float(evAtNodes(subst(vv=-1,vTrans[2]),[surfNodes[i]],surfVars))[1]*ptConfNodal[5][conf_node] + float(evAtNodes(subst(vv=-1,vTrans[3]),[surfNodes[i]],surfVars))[1]*ptConfNodal[8][conf_node],
      omega_23 : float(evAtNodes(subst(vv=-1,vTrans[1]),[surfNodes[i]],surfVars))[1]*ptConfNodal[3][conf_node] + float(evAtNodes(subst(vv=-1,vTrans[2]),[surfNodes[i]],surfVars))[1]*ptConfNodal[6][conf_node] + float(evAtNodes(subst(vv=-1,vTrans[3]),[surfNodes[i]],surfVars))[1]*ptConfNodal[9][conf_node],
      if (dir = 1) then (
        PI_dH_dz_l : float(evAtNodes(subst(vv=-1,diff(hamil,varsV[2])*dv1_inv[2]),[surfNodes[i]],surfVars)),
        Pi_dH_dz : Pi_dH_dz + omega_12*PI_dH_dz_l[1],
        PI_dH_dz_l : float(evAtNodes(subst(vv=-1,diff(hamil,varsV[3])*dv1_inv[3]),[surfNodes[i]],surfVars)),
        Pi_dH_dz : Pi_dH_dz + omega_13*PI_dH_dz_l[1]
      )
      else if (dir = 2) then (
        PI_dH_dz_l : float(evAtNodes(subst(vv=-1,diff(hamil,varsV[1])*dv1_inv[1]),[surfNodes[i]],surfVars)),
        Pi_dH_dz : Pi_dH_dz - omega_12*PI_dH_dz_l[1],
        PI_dH_dz_l : float(evAtNodes(subst(vv=-1,diff(hamil,varsV[3])*dv1_inv[3]),[surfNodes[i]],surfVars)),
        Pi_dH_dz : Pi_dH_dz + omega_23*PI_dH_dz_l[1]
      )
      else if (dir = 3) then (
        PI_dH_dz_l : float(evAtNodes(subst(vv=-1,diff(hamil,varsV[1])*dv1_inv[1]),[surfNodes[i]],surfVars)),
        Pi_dH_dz : Pi_dH_dz - omega_13*PI_dH_dz_l[1],
        PI_dH_dz_l : float(evAtNodes(subst(vv=-1,diff(hamil,varsV[2])*dv1_inv[2]),[surfNodes[i]],surfVars)),
        Pi_dH_dz : Pi_dH_dz - omega_23*PI_dH_dz_l[1]
      )
    ),
    printf(fh, "  alpha_quad[~a] += ~a; ~%", i-1, float(Pi_dH_dz))
  ),
  printf(fh, "~%"),

  printf(fh, "} ~%")
)$ 