/* Generate header file for gyrokinetic_pol_density kernels. */
load(stringproc)$

/* ...... USER INPUTS........ */

/* Serendipity basis. */
minPolyOrder_Ser : 1$
maxPolyOrder_Ser : 1$
minCdim_Ser : 1$
maxCdim_Ser : 3$

/* Tensor product basis. */
/* Note that Serendipity, p = 1, is equivalent to Tensor */
/* Thus no need to calculate p = 1 Tensor basis */
minPolyOrder_Tensor : 2$
maxPolyOrder_Tensor : 2$
minCdim_Tensor : 1$
maxCdim_Tensor : 0$

/* ...... END OF USER INPUTS........ */

/* To generate other bases, just add corresponding column to arrays below. */
bName        : ["ser", "tensor"]$
minPolyOrder : [minPolyOrder_Ser, minPolyOrder_Tensor]$
maxPolyOrder : [maxPolyOrder_Ser, maxPolyOrder_Tensor]$
minCdim      : [minCdim_Ser, minCdim_Tensor]$
maxCdim      : [maxCdim_Ser, maxCdim_Tensor]$

fh : openw("~/max-out/gkyl_gyrokinetic_pol_density_kernels.h")$
printf(fh, "#pragma once~%")$
printf(fh, "~%")$

printf(fh, "#include <gkyl_util.h>~%")$
printf(fh, "~%")$

printf(fh, "EXTERN_C_BEG~%")$
printf(fh, "~%")$

for bInd : 1 thru length(bName) do (

  for cd : minCdim[bInd] thru maxCdim[bInd] do (
    for polyOrder : minPolyOrder[bInd] thru maxPolyOrder[bInd] do (
      funcName : sconcat("gkyl_gyrokinetic_pol_density_",cd,"x_",bName[bInd],"_p",polyOrder),
      printf(fh, "GKYL_CU_DH void ~a(const double *dx, const double *epsilon, const double *phi, double *out);~%", funcName)
    )
  ),
  printf(fh, "~%")

)$

printf(fh, "EXTERN_C_END~%")$
printf(fh, "~%")$
close(fh)$
