/*load("metric_calculation/calc-metric.mac")$*/
/*load("metric_calculation/calc-metric-skin.mac")$*/
/*load("metric_calculation/2cell-calc-metric-skin.mac")$*/
load("metric_calculation/calc-metric-skin-bcs.mac")$
load(stringproc)$

load("bvp_utilities/bvp-util");
load("fem/fem-util");


/* ...... USER INPUTS........ */

/* Serendipity basis. */
minPolyOrder_Ser : 1$
maxPolyOrder_Ser : 1$
minCdim_Ser : 3$
maxCdim_Ser : 3$

/* ...... END OF USER INPUTS........ */

bName        : ["Ser","Tensor"]$
minPolyOrder : [minPolyOrder_Ser, minPolyOrder_Tensor]$
maxPolyOrder : [maxPolyOrder_Ser, maxPolyOrder_Tensor]$
minCdim      : [minCdim_Ser, minCdim_Tensor]$
maxCdim      : [maxCdim_Ser, maxCdim_Tensor]$


for bInd : 1 thru 1 do (
  for cD : minCdim[bInd] thru maxCdim[bInd] do (
      for polyOrder : minPolyOrder[bInd] thru maxPolyOrder[bInd] do (
          disp(printf(false,sconcat("Creating gij_calc_",bName[bInd]," ~axp~a"),cD,polyOrder)),
          fName : sconcat("~/max-out/gij_calc_", bName[bInd], "_", cD, "x_",  "p", polyOrder, ".c"),
          fh : openw(fName),
          printf(fh, "#include \"gkyl_calc_metric_kernels.h\"~%~%"),
          printf(fh, "static inline double calc_metric(double dxdz[~a][~a], int i, int j) ~%", cD, cD),
          printf(fh, "{ double sum = 0;   for (int k=0; k<~a; ++k) sum += dxdz[k][i-1]*dxdz[k][j-1]; return sum; } ~%~%", cD),
          calcMetricCoeffs(fh, cD, bName[bInd], polyOrder),
          close(fh)
    )
  )
);
