load("maxwell/em-vars-limiter")$
load(stringproc)$
/* This script calls the functions which generate the kernels for 
   limiting the slopes of the EM variables in DG Maxwell's equations. */

/* ...... USER INPUTS........ */

/* Tensor product basis. */
minPolyOrder_Tensor : 1$
maxPolyOrder_Tensor : 1$
minCdim_Tensor : 1$
maxCdim_Tensor : 3$

/* ...... END OF USER INPUTS........ */

cvars : [x, y, z]$

for d : minCdim_Tensor thru maxCdim_Tensor do (
  for polyOrder : minPolyOrder_Tensor thru maxPolyOrder_Tensor do (
    disp(printf(false,sconcat("Creating EM limiter funcs ",bName[bInd]," ~axp~a"),d,polyOrder)),

    for dir : 1 thru d do ( 
      fname : sconcat("~/max-out/em_vars_limiter_", cvars[dir], "_", d, "x_", "tensor_p", polyOrder, ".c"),
      fh : openw(fname),
      funcName : sconcat("em_vars_limiter_", cvars[dir],"_", d, "x_", "tensor_p", polyOrder),
      calcMaxwellLimiter(dir, fh, funcName, d, polyOrder),
      close(fh)
    )
  )
);
