load("basis-calc/basis-expSqrtSignFuncs")$
load(stringproc)$
/* This script calls the functions which calculate the
    DG expansion of sqrt(A) where A is a DG field
    by projecting A onto quadrature points, taking the sqrt,
    and then projecting back onto the modal basis. */

/* ...... USER INPUTS........ */

/* Serendipity basis. */
minPolyOrder_Ser : 1$
maxPolyOrder_Ser : 2$
minCdim_Ser : 1$
maxCdim_Ser : 3$

/* Tensor product basis. */
/* Note that Serendipity, p = 1, is equivalent to Tensor */
/* Thus no need to calculate p = 1 Tensor basis */
minPolyOrder_Tensor : 2$
maxPolyOrder_Tensor : 2$
minCdim_Tensor : 1$
maxCdim_Tensor : 0$

/* ...... END OF USER INPUTS........ */

bName        : ["ser","tensor"]$
minPolyOrder : [minPolyOrder_Ser, minPolyOrder_Tensor]$
maxPolyOrder : [maxPolyOrder_Ser, maxPolyOrder_Tensor]$
minCdim      : [minCdim_Ser, minCdim_Tensor]$
maxCdim      : [maxCdim_Ser, maxCdim_Tensor]$

for bInd : 1 thru length(bName) do (
  for d : minCdim[bInd] thru maxCdim[bInd] do (
    minPolyOrderB : minPolyOrder[bInd],
    maxPolyOrderB : maxPolyOrder[bInd],
    /* Optional parameter to make the quadrature higher order
       Actually seems to have *worse* properties than just polyOrder + 1 
       quadrature points */
    /* quadPolyOrder : 4, */
    if (d=3 and maxPolyOrderB > 1) then maxPolyOrderB : 1,

    for polyOrder : minPolyOrderB thru maxPolyOrderB do (
      fname : sconcat("~/max-out/gkyl_basis_",  bName[bInd], "_", d, "x_p", polyOrder, "_sqrt_with_sign.h"),
      fh : openw(fname),
      funcName : sconcat(bName[bInd], "_", d, "x_p", polyOrder, "_sqrt_with_sign"),
      calcDGExpSqrtSign(fh, funcName, d, bName[bInd], polyOrder, polyOrder),
      close(fh)
    )
  )
);
