/* Create kernels to project a Maxwellian onto the DG basis using quadrature. */
load("deflate_geo/deflate-geo.mac")$
load(stringproc)$


/* ...... USER INPUTS........ */

/* Serendipity basis. */
minPolyOrder_Ser : 1$
maxPolyOrder_Ser : 2$

/* ...... END OF USER INPUTS........ */

bName        : ["ser"]$
minPolyOrder : [minPolyOrder_Ser]$
maxPolyOrder : [maxPolyOrder_Ser]$

for bInd : 1 thru length(bName) do (
  for polyOrder : minPolyOrder[bInd] thru maxPolyOrder[bInd] do (
    disp(printf(false,sconcat("Creating deflate_geo_calc_",bName[bInd]," ~axp~a"),cD,polyOrder)),
    fName : sconcat("~/max-out/deflate_geo_", bName[bInd], "_", "p", polyOrder, ".c"),
    fh : openw(fName),
    printf(fh, "#include \"gkyl_deflate_geo_kernels.h\"~%~%"),
    deflateGeo(fh, bName[bInd], polyOrder),
    close(fh)
  )
);
