/* Create kernels to project a Maxwellian onto the DG basis using quadrature. */

load("maxwellian_on_basis/maxwellianGaussQuad.mac")$
load(stringproc)$


/* ...... USER INPUTS........ */

/* Serendipity basis. */
minPolyOrder_Ser : 1$
maxPolyOrder_Ser : 2$
minCdim_Ser : 1$
minVdim_Ser : 1$    /* see beginning of v loop below though. */
maxCdim_Ser : 3$
maxVdim_Ser : 3$

/* Tensor product basis. */
minPolyOrder_Tensor : 2$ /* No need to generate p=1. */
maxPolyOrder_Tensor : 2$
minCdim_Tensor : 1$
minVdim_Tensor : 1$    /* see begining of v loop below though. */
maxCdim_Tensor : 0$
maxVdim_Tensor : 0$

/* ...... END OF USER INPUTS........ */

bName        : ["Ser","Tensor"]$
minPolyOrder : [minPolyOrder_Ser, minPolyOrder_Tensor]$
maxPolyOrder : [maxPolyOrder_Ser, maxPolyOrder_Tensor]$
minCdim      : [minCdim_Ser, minCdim_Tensor]$
minVdim      : [minVdim_Ser, minVdim_Tensor]$
maxCdim      : [maxCdim_Ser, maxCdim_Tensor]$
maxVdim      : [maxVdim_Ser, maxVdim_Tensor]$

for bInd : 1 thru length(bName) do (
  for cD : minCdim[bInd] thru maxCdim[bInd] do (
    for vD : max(cD,minVdim[bInd]) thru maxVdim[bInd] do (

      maxPolyOrderB : maxPolyOrder[bInd],
      if (cD+vD=6 and maxPolyOrderB > 1) then maxPolyOrderB : 1,

      for polyOrder : minPolyOrder[bInd] thru maxPolyOrder[bInd] do (
        /* Create a separate file for gyrokinetics in 3x2v. */
        if (cD = 3) then (
          disp(printf(false,sconcat("Creating MaxwellianOnBasis",bName[bInd]," ~ax~avP~a"),cD,2,polyOrder)),
          fname : sconcat("~/max-out/MaxwellianOnBasis", bName[bInd], cD, "x", 2, "vP", polyOrder, ".cpp"),
          fh : openw(fname),
          printf(fh, "#include <MaxwellianOnBasisModDecl.h>~%~%"),
          isGK : true,
          funcName : sconcat("GkMaxwellianOnBasisGauss", cD, "x", 2, "v", bName[bInd]),
          calcMaxwellianProjGauss(fh, funcName, cD, 2, bName[bInd], polyOrder, isGK),
          close(fh)
        )

      )
    )
  )
);
